/* global process, Buffer */
import { expect, test } from '@playwright/test'
import { expand, signIn } from './support.js'

test('lawyer PDF, visit report and fee claim persist and are reviewed by DLAO', async ({ page, request }) => {
  test.setTimeout(120000)
  const actors = JSON.parse(process.env.E2E_ACTORS)
  const login = async (role) => ({ authorization: `Bearer ${(await (await request.post('/api/auth/login', { data: actors[role] })).json()).token}` })
  const officer = await login('DLAO_OFFICER')
  const lawyer = await login('PANEL_LAWYER')
  const helpline = await login('HELPLINE_AGENT')
  const submitted = await request.post('/api/applications', { headers: helpline, data: { applicantName: 'Fictional Lawyer Workspace Applicant' } })
  expect(submitted.status()).toBe(201)
  const { applicationId } = await submitted.json()
  for (const [path, data] of [['review', { reviewState: 'READY_FOR_DECISION', reason: 'Fictional intake reviewed by the human officer.' }], ['accept', { reason: 'Human officer accepted the fictional lawyer workspace Case.' }]]) expect((await request.post(`/api/applications/${applicationId}/${path}`, { headers: officer, data })).ok()).toBeTruthy()
  const management = await (await request.get(`/api/lawyers/applications/${applicationId}`, { headers: officer })).json()
  const offer = await request.post(`/api/lawyers/applications/${applicationId}/assignments`, { headers: officer, data: { lawyerUserId: management.panelLawyers.find(({ displayName }) => displayName === 'Fictional Panel lawyer').id, reason: 'Fictional lawyer workspace assignment.' } })
  expect(offer.status()).toBe(201)
  const { assignmentId } = await offer.json()
  const base = `/api/lawyers/assignments/${assignmentId}`
  expect((await request.post(`${base}/respond`, { headers: lawyer, data: { decision: 'ACCEPT', reason: 'I accept this fictional lawyer workspace Case.' } })).ok()).toBeTruthy()
  const { caseId } = management
  await signIn(page, 'PANEL_LAWYER')
  await page.getByRole('link', { name: new RegExp(`^${caseId}`) }).first().click()
  await expect(page.getByRole('heading', { name: 'Progress Update Form' })).toBeVisible()
  await page.getByLabel('Document label', { exact: true }).fill('Fictional court order attachment')
  await page.getByLabel('Folder', { exact: true }).selectOption('ORDERS')
  await page.getByLabel('PDF attachment (maximum 4 MB)').setInputFiles({ name: 'fictional-order.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\n1 0 obj << /Type /Catalog >> endobj\ntrailer << /Root 1 0 R >>\n%%EOF\n') })
  await page.getByRole('button', { name: 'Upload document', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'PDF uploaded for DLAO review' })).toBeVisible()
  await page.getByLabel('Applicant contacted', { exact: true }).check()
  await page.getByLabel('Documents checked by lawyer', { exact: true }).check()
  await page.getByLabel('Legal advice provided', { exact: true }).check()
  await page.getByLabel('Case progress', { exact: true }).selectOption('HEARING_ATTENDED')
  await page.getByLabel('Legal action taken / Notes').fill('Fictional hearing attended and court order discussed.')
  await page.getByLabel('Next action', { exact: true }).fill('Review the next court hearing date with the office.')
  const visit = page.getByRole('heading', { name: 'Progress Update Form' }).locator('..')
  await visit.getByLabel(/Fictional court order attachment/).check()
  await page.getByRole('button', { name: 'Submit visit report', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Progress report recorded' })).toBeVisible()
  await page.getByLabel('Payment stage', { exact: true }).selectOption('HEARING_ATTENDANCE')
  await page.getByLabel('Claim amount (BDT)').fill('500.50')
  await page.getByLabel('Claim details', { exact: true }).fill('Fictional hearing attendance claim backed by the court order.')
  const payment = page.getByRole('heading', { name: new RegExp(`Stage-wise payment report.*${caseId}`) }).locator('..')
  await payment.getByLabel(/Fictional court order attachment/).check()
  await page.getByRole('button', { name: 'Submit claim', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Fee claim submitted for review' })).toBeVisible()
  await page.reload()
  await expect(page.getByText('Fictional hearing attended and court order discussed.')).toBeVisible()
  await expect(page.getByText('Fictional hearing attendance claim backed by the court order.', { exact: true })).toBeVisible()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download PDF', exact: true }).click()
  expect((await download).suggestedFilename()).toBe('fictional-order.pdf')
  await page.setViewportSize({ width: 360, height: 800 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.setViewportSize({ width: 1280, height: 900 })

  await signIn(page, 'DLAO_OFFICER')
  await page.goto(`/applications/${applicationId}`)
  await expand(page, 'Lawyer reports, documents and fee claims')
  const workspaceRegion = page.getByRole('region', { name: /Reports, documents and payments/ })
  await expect(workspaceRegion.getByText('Fictional hearing attended and court order discussed.')).toBeVisible()
  const document = workspaceRegion.locator('article').filter({ hasText: 'Fictional court order attachment' }).filter({ has: page.getByRole('button', { name: 'Download PDF', exact: true }) }).first()
  await document.getByLabel('Officer review reason').fill('Officer reviewed the fictional order PDF.')
  await document.getByRole('button', { name: 'Approve', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Document review recorded' })).toBeVisible()
  const claim = workspaceRegion.locator('article').filter({ hasText: 'Fictional hearing attendance claim backed by the court order.' })
  await claim.getByLabel('Officer review reason').fill('Officer approved the fictional stage claim.')
  await claim.getByLabel('Approved amount (BDT)').fill('450.50')
  await claim.getByRole('button', { name: 'Approve', exact: true }).click()
  await expect(claim.getByLabel('Payment reference (demo record)')).toBeVisible()
  await claim.getByLabel('Officer review reason').fill('Fictional payment recorded after review.')
  await claim.getByLabel('Amount being recorded as paid (BDT)').fill('450.50')
  await claim.getByLabel('Payment reference (demo record)').fill('DEMO-BROWSER-1')
  await claim.getByRole('button', { name: 'Record payment', exact: true }).click()
  await expect(claim.getByRole('heading')).toContainText('Paid')
  const beforePrint = page.evaluate(() => { window.print = () => { window.__lawyerPrint = Boolean(document.querySelector('.lawyer-print-sheet.print-active')); } })
  await beforePrint
  await page.getByRole('button', { name: 'Print report / Save as PDF' }).click()
  expect(await page.evaluate(() => window.__lawyerPrint)).toBeTruthy()
  const workspace = await (await request.get(`${base}/workspace`, { headers: officer })).json()
  expect(workspace.totals).toEqual({ claimed: 500.50, approved: 450.50, paid: 450.50, pendingApproved: 0 })
  // All internal dashboard links still resolve after the workflow changed.
  const links = await page.locator('a[href^="/"]').evaluateAll((items) => [...new Set(items.map((item) => item.getAttribute('href')))])
  for (const href of links) expect((await request.get(href)).ok(), href).toBeTruthy()
})
